# Generated by Django 4.2.3 on 2024-03-26 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_email_remove_profile_first_name_and_more'),
        ('course', '0002_alter_course_id_alter_course_lecturer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lecturer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
    ]
