# Generated by Django 4.2.3 on 2024-03-30 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='creator',
        ),
        migrations.AddField(
            model_name='event',
            name='related_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='classes.class'),
        ),
    ]
