# Generated by Django 4.2.3 on 2024-04-05 02:56

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_related_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_address',
            field=django_google_maps.fields.AddressField(max_length=200, null=True),
        ),
    ]
