# Generated by Django 4.2.3 on 2024-05-28 03:16

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='lng',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
