# Generated by Django 4.2.3 on 2024-05-28 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_lat_event_lng_alter_event_geolocation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='lat',
            new_name='checkpoint_lat',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='lng',
            new_name='checkpoint_lng',
        ),
    ]
