# Generated by Django 4.2.3 on 2024-05-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_rename_lat_event_checkpoint_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='checkpoint_lat',
            field=models.DecimalField(decimal_places=7, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='checkpoint_lng',
            field=models.DecimalField(decimal_places=7, max_digits=15, null=True),
        ),
    ]
